### ISSUE TITLE
If possible design algorithm for running learning algorithm on each level in hierarchy with smallest heap footprint

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/WalnutiQ#174]

**Comment by quinnliu** [comment]
Trying to create `BigNeocortex` and `BigNervousSystem` classes with same public API but never exceeding a heap memory threshold initially set in constructor.

**Comment by quinnliu** [comment]
<b>Next Action:</b>

**Comment by quinnliu** [comment]
<b>Next Action:</b> Work on instantiating 2 Regions, connecting them then writing them to disk.

**Comment by quinnliu** [comment]
<b>Next Action:</b> Work on instantiating currentRegion and connectPatternRegion, connecting them. 
Possibly adding them to a directed graph model of BigNeocortex for correct traversing later then writing them to disk.

**Comment by quinnliu** [comment]
<b>Next Action:</b> Implemented public API for BigNeocortex

**Comment by quinnliu** [comment]
<b>Next Action:</b> Work on instantiating currentRegion and connectPatternRegion, connecting them. 
Possibly adding them to a directed graph model of BigNeocortex for correct traversing later then writing them to disk.

**Comment by quinnliu** [comment]
Yo guess what I am talking to myself online. whow.

**Comment by quinnliu** [comment]
<b>Note:</b> Since the Retina is 1 big object it can't really be split up into separate pieces like regions in the neocortex. But it still needs to be written to disk.

**Comment by quinnliu** [comment]
<b>Note:</b> Still talking to myself. Created a BigRetina class with same public API. I think this will work well.

**Comment by quinnliu** [comment]
<b>PRO TIP:</b> Stop thinking your a smart ass and don't need to unit test the crap out of your code. You can't think of everything.

**Comment by quinnliu** [comment]
![intellij_vm_window](https://cloud.githubusercontent.com/assets/2585159/8191714/aa5f6e78-1437-11e5-9ddb-0b82a6ac69ef.jpg)

**Comment by quinnliu** [comment]
<b>Next Action:</b> Get BigNeocortex to be created with large number of big regions.

<b>Next Action:</b> Get BigNervousSystem to instantiate with a upper level heap usage size. Not reasonable to make BigNervousSystem public API the same as NervousSystem right now with all the unimplemented classes inbetween. May be wise to do this in the future.

**Comment by quinnliu** [comment]
<b>Next Action:</b> Get BigNervousSystem to instantiate with a upper level heap usage size. Not reasonable to make BigNervousSystem public API the same as NervousSystem right now with all the unimplemented classes inbetween. May be wise to do this in the future.

**Comment by quinnliu** [comment]
```
Running Experiment_1.main() ...
heapMaxSize = 3817 MB
usedHeapSize = 21 MB
currentRunTimeInSeconds = 0.0
usedHeapSize = 468 MB
currentRunTimeInSeconds = 4.987
AFTER: instantiateAndSaveAllUnconnectedRegions
                (regionParameterListInOrder);
usedHeapSize = 518 MB
currentRunTimeInSeconds = 5.306
AFTER: Region childRegion = this.getRegion(connectionParameterListInOrder[i+4]);
usedHeapSize = 464 MB
currentRunTimeInSeconds = 7.707
AFTER: addToCurrentRegion(rectanglePartOfParentRegionToConnectTo, A,
                        numberOfColumnsToOverlapAlongNumberOfRows, numberOfColumnsToOverlapAlongNumberOfColumns);
usedHeapSize = 517 MB
currentRunTimeInSeconds = 7.767
AFTER: Region childRegion = this.getRegion(connectionParameterListInOrder[i+4]);
usedHeapSize = 825 MB
currentRunTimeInSeconds = 11.951
AFTER: addToCurrentRegion(rectanglePartOfParentRegionToConnectTo, B,
                        numberOfColumnsToOverlapAlongNumberOfRows, numberOfColumnsToOverlapAlongNumberOfColumns);
usedHeapSize = 1049 MB
currentRunTimeInSeconds = 12.271
AFTER: Region childRegion = this.getRegion(connectionParameterListInOrder[i+4]);
usedHeapSize = 1045 MB
currentRunTimeInSeconds = 27.514
AFTER: addToCurrentRegion(rectanglePartOfParentRegionToConnectTo, F,
                        numberOfColumnsToOverlapAlongNumberOfRows, numberOfColumnsToOverlapAlongNumberOfColumns);
usedHeapSize = 1271 MB
currentRunTimeInSeconds = 45.787
AFTER: Region childRegion = this.getRegion(connectionParameterListInOrder[i+4]);
usedHeapSize = 1192 MB
currentRunTimeInSeconds = 51.616
AFTER: addToCurrentRegion(rectanglePartOfParentRegionToConnectTo, H,
                        numberOfColumnsToOverlapAlongNumberOfRows, numberOfColumnsToOverlapAlongNumberOfColumns);
usedHeapSize = 1192 MB
currentRunTimeInSeconds = 51.657
AFTER: connectAllRegions(connectionParameterListInOrder);
heapMaxSize = 3817 MB
usedHeapSize = 1192 MB
currentRunTimeInSeconds = 0.0
AFTER: this.bigNeocortex = bigNeocortex;
usedHeapSize = 489 MB
currentRunTimeInSeconds = 1.852
AFTER: BigRetina bigRetina = new BigRetina((int) retinaDimension.getHeight(), (int) retinaDimension.getWidth(), pathAndRetinaFileName);
usedHeapSize = 398 MB
currentRunTimeInSeconds = 7.287
AFTER: Region region = this.bigNeocortex.getRegion(
                    retinaConnectionParameterListInOrder[i+4]);
usedHeapSize = 1590 MB
currentRunTimeInSeconds = 148.967
AFTER: opticNerveConnectType.connect(sensorCells, regionColumns,
                    numberOfColumnsToOverlapAlongXAxisOfSensorCells,
                    numberOfColumnsToOverlapAlongYAxisOfSensorCells);
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:587)
	at java.lang.StringBuffer.append(StringBuffer.java:332)
	at java.io.StringWriter.write(StringWriter.java:77)
	at com.google.gson.stream.JsonWriter.beforeName(JsonWriter.java:582)
	at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:401)
	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:495)
	at com.google.gson.Gson$3.write(Gson.java:265)
	at com.google.gson.Gson$3.write(Gson.java:250)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:89)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:195)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:89)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:195)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:89)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:195)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:93)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:93)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:89)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:195)
	at com.google.gson.Gson.toJson(Gson.java:593)
	at com.google.gson.Gson.toJson(Gson.java:572)

Process finished with exit code 1

```

**Comment by quinnliu** [comment]
<b>Next Action:</b> Heap analyzation about:
```
opticNerveConnectType.connect(sensorCells, regionColumns,
                    numberOfColumnsToOverlapAlongXAxisOfSensorCells,
                    numberOfColumnsToOverlapAlongYAxisOfSensorCells);
```

**Comment by quinnliu** [comment]
<b>Next Action:</b> Test weather setting objects no longer in use to null actually reduces heap size and run time. 

code being tested in BigNervousSystem constructor:
```
            sensorCells = null;
            region = null;
            regionColumns = null;
```

**Comment by quinnliu** [comment]
This iissue is done for now until it is really important to have overlap between retina's that are 1000*1000 vision cells with regions taking in vision input.
